### ISSUE TITLE
Error while parsing entities from JDL || ignite generate import-jdl ||

### ISSUE THREAD

**Issue by grajuu** [ruddell/ignite-jhipster#96] opened 2020-05-15 15:33 UTC
Hey @ruddell 

 I tried import jdl 

  `ignite generate import-jdl ../issue0034.jh`

but the process get stopped with out importing.

```
$ ignite generate import-jdl ../mySchool.jh
The JDL is being parsed.
warn: An Entity name 'User' was used: 'User' is an entity created by default by JHipster. All relationships toward it will be kept but any attributes and relationships from it will be disregarded.
The JDL has been successfully parsed
Found entities: Members, Rewards, Address, Product, ProductCategory, ProductOrder, OrderItem, Invoice, Shipment.
Generating Members
Error while parsing entities from JDL


Error: ENOENT: no such file or directory, open '.jhipster/Members.json'
```
![image](https://user-images.githubusercontent.com/44188062/82067835-dc434380-96ee-11ea-9f95-bf3bf3fdc090.png)

----  Below is my JDL

```
application {
  config {
    baseName gateway,
    packageName com.sample.gateway,
    applicationType gateway,
    authenticationType oauth2,
    prodDatabaseType postgresql,
    searchEngine elasticsearch,
    serviceDiscoveryType eureka,
    testFrameworks [protractor],
    buildTool maven,
    clientFramework react,
    nativeLanguage en,
    languages [en, es] 
  }
  entities Members, Rewards, Address, Product, ProductCategory, ProductOrder, OrderItem, Invoice, Shipment
}

application {
  config {
    baseName school,
    packageName com.sample.users,
    applicationType microservice,
    authenticationType oauth2,
    prodDatabaseType postgresql,
    searchEngine elasticsearch,
    buildTool maven,
    serverPort 8081,
    serviceDiscoveryType eureka
  }
  entities Members, Rewards, Address
}

application {
  config {
    baseName store,
    packageName com.sample.store,
    applicationType microservice,
    authenticationType oauth2,
    databaseType mongodb,
    devDatabaseType mongodb,
    prodDatabaseType mongodb,
    searchEngine elasticsearch,
    buildTool maven,
    enableHibernateCache false,
    serverPort 8082,
    serviceDiscoveryType eureka
  }
 entities Product, ProductCategory, ProductOrder, OrderItem
}

application {
  config {
    baseName invoice,
    applicationType microservice,
    packageName com.sample.invoice,
    authenticationType oauth2,
    prodDatabaseType postgresql,
    buildTool maven,
    serverPort 8083,
    serviceDiscoveryType eureka
  }
  entities Invoice, Shipment
}


// Customer for the store
entity Members {
  firstName String required,
    lastName String required,
    gender Gender required,
    who Who required,
    email String required pattern(/^[^@\s]+@[^@\s]+\.[^@\s]+$/)
    age BigDecimal
}
// Address table for both Student and Faculty 
entity Address{
  addressLine1 String,
    addressLine2 String,
    city String,
    country String,
    primaryPhone String ,
    secondryPhone String
}
enum Gender {
  MALE, FEMALE, OTHER
}
enum Who {
  STUDENT, FACULTY, ADMIN
}
entity Rewards {
  facultyName String ,
        studentName String,
        timestamp ZonedDateTime required,
        rewardReceved BigDecimal,
        date Instant required,
        content TextBlob required
}
/**
 * Entities for store microservice
 */
// Product sold by the Online store 
entity Product {
  name String required
    description String
    price BigDecimal required min(0)
    size Size required
    image ImageBlob
}
enum Size {
  S, M, L, XL, XXL
}
entity ProductCategory {
  name String required,
    description String
}
entity ProductOrder {
  placedDate Instant required,
    email String required pattern(/^[^@\s]+@[^@\s]+\.[^@\s]+$/),
    status OrderStatus required,
    code String required,
    invoiceId Long,
    customer String required
}
enum OrderStatus {
  COMPLETED, PENDING, CANCELLED
}
entity OrderItem {
  quantity Integer required min(0)
    totalPrice BigDecimal required min(0)
    status OrderItemStatus required
}
enum OrderItemStatus {
  AVAILABLE, OUT_OF_STOCK, BACK_ORDER
}
/* Entities for Invoice microservice */
entity Invoice {
  code String required
    date Instant required
    details String
    status InvoiceStatus required
    paymentMethod PaymentMethod required
    paymentDate Instant required
    paymentAmount BigDecimal required
}
enum InvoiceStatus {
  PAID, ISSUED, CANCELLED
}
entity Shipment {
  trackingCode String
    date Instant required
    details String
}
enum PaymentMethod {
  CREDIT_CARD, CASH_ON_DELIVERY, PAYPAL
}
/* Entities for notification microservice */
entity Notification {
  date Instant required
    details String
    sentDate Instant required
    format NotificationType required
    userId Long required
    productId Long required
}
enum NotificationType {
  EMAIL, SMS, PARCEL
}
relationship ManyToOne {
  OrderItem{product(name) required} to Product
}
relationship OneToMany {
  Members{address} to Address{members(email) required} ,
  Members{rewards} to Rewards{members(email) required} ,
  ProductOrder{orderItem} to OrderItem{order(code) required} , 
  ProductCategory{product} to Product{productCategory(name)},
  Invoice{shipment} to Shipment{invoice(code) required}
}
relationship OneToOne {
  Members{user(login) required} to User
}
service Invoice, Shipment, Product, ProductCategory, ProductOrder, OrderItem with serviceClass
paginate Invoice, Shipment, Product, Members, ProductOrder, OrderItem with pagination
// MicroServices 
microservice Product, ProductOrder, ProductCategory, OrderItem with store
microservice Members, Address, Rewards with school
microservice Invoice, Shipment with invoice
microservice Notification with notification
// will be created under 'docker-compose' folder
deployment {
  deploymentType docker-compose
  appsFolders [gateway, school, store, invoice]
  dockerRepositoryName "govindraju9999"
  consoleOptions [zipkin]
}
```

**Comment by ruddell** [comment] 2020-05-16 15:03
There was lack of support for JDL containing multiple applications or deployments.  Fixed by 89fb95d03c19524c836afce1742df7af262aedf1, I tested it with a few JDL files and it seemed to work for all the cases.

So now you can import the entities from a JDL file with multiple applications/deployments 👍

Thanks again!

**Closed by ruddell** 2020-05-16 15:03 UTC

**Comment by grajuu** [comment] 2020-05-19 12:55
Hey @ruddell ,
  I found something strange after updating.

first : i ran the below to update my ignite version 

`npm i -g ignite-cli@3.5.1 ignite-jhipster@3.5.4 `

![image](https://user-images.githubusercontent.com/44188062/82328080-094c6a80-99fd-11ea-9b29-2650669063e1.png)


Then i check `ignite --version`
its still `3.5.1`
![image](https://user-images.githubusercontent.com/44188062/82328270-43b60780-99fd-11ea-8d30-9d07cfad6301.png)
**--------------------  Shows topper is ------------**
i ran 
 `ignite new HelloSchool --boilerplate ignite-jhipster`

it fail to add 
`failed to add React Native 0.61.5`

![image](https://user-images.githubusercontent.com/44188062/82328673-c939b780-99fd-11ea-88ac-876d0860dece.png)

Please let me know if i did something illegal .

-- Thanks.

**Comment by ruddell** [comment] 2020-05-19 14:16
Could you try again please, also pass the `--debug` flag to the generation command?  That should give you a better error message than just `failed to add React Native 0.61.5`

    ignite new HelloSchool --boilerplate ignite-jhipster --debug

I couldn't reproduce on my computer but the logs from the `--debug` flag should help find the reason for failure.

**Comment by grajuu** [comment] 2020-05-19 15:05
Sure 

```
🔥 igniting app HelloSchool
15:02:17 [ignite] making directory /Users/mardubudi/Documents/PBIS-REPO/tis-jhip/tis-mySchool/HelloSchool
15:02:17 [ignite] switched directory to /Users/mardubudi/Documents/PBIS-REPO/tis-jhip/tis-mySchool/HelloSchool
15:02:17 [ignite] running boilerplate-install command
15:02:17 [ignite] installing plugin ignite-jhipster from npm
⠧ adding ignite-jhipster15:02:21 [ignite] ignite-jhipster 3.5.5 on npm.
15:02:21 [ignite] yarn add ignite-jhipster --dev
⠇ adding ignite-jhipster15:02:31 [ignite] finished yarn command
⠋ installing boilerplate15:02:31 [ignite] reading boilerplate package.json
15:02:31 [ignite] loading boilerplate install script from /Users/mardubudi/Documents/PBIS-REPO/tis-jhip/tis-mySchool/HelloSchool/node_modules/ignite-jhipster/boilerplate.js
15:02:32 [ignite] running install function from boilerplate
✔ Generating a React Native client for JHipster apps
✔ Enter the path to your JHipster project root directory: · gateway
Looking for ../gateway/.yo-rc.json
Found JHipster config file at gateway/.yo-rc.json
✔ Do you want to enable end-to-end tests with Detox? (y/N) · true
Using yarn as the package manager
15:02:46 [ignite] initializing react native
15:02:46 [ignite] npx react-native init HelloSchool --version 0.61.5
15:02:46 [ignite] initializing react native project
15:02:46 [ignite] command: npx react-native init HelloSchool --version 0.61.5
Cannot find module '/usr/local/lib/node_modules/react-native-cli/node_modules/prompt/lib/prompt'. Please verify that the package.json has a valid "main" entry
✖ failed to add React Native 0.61.5
Please try again with the --debug flag for a more verbose error
mardubudi@Govinds-MacBook-Air tis-mySchool %
```

![image](https://user-images.githubusercontent.com/44188062/82343147-19ba1080-9a10-11ea-862e-3582b2181709.png)

**Comment by grajuu** [comment] 2020-05-19 15:55
is it some thing specific to my system ..? may be upgrading issue ..?

**Comment by ruddell** [comment] 2020-05-19 16:08
Do you have `react-native-cli` installed globally? I see that package in the error message.  You can check with `which react-native` and `ls -al $(which react-native)` to see the full path if it does exist.
> If you previously installed a global react-native-cli package, please remove it as it may cause unexpected issues.
https://reactnative.dev/docs/environment-setup

It works on my Mac and the CI (which tests iOS and Android apps on Mac, and generation on Ubuntu). So I'm guessing something related to your system.  Not sure.

**Comment by grajuu** [comment] 2020-05-19 16:18
Sure @ruddell  i will give a try.
--Thanks.

**Comment by grajuu** [comment] 2020-05-19 17:30
My node got corrupted i think so , i reinstalled it again .
Now i start a sample it start working now.
thanks   

i remove `react-native-cli` which is not required as React-Native documentation you suggested.

Last quick question.

npm i -g ignite-cli@3.5.1 ignite-jhipster@3.5.4 

is different from 
`ignite --version`
`3.5.1`

Do we have command for confirming/checking `ignite-jhipster ` version ..?

**Comment by ruddell** [comment] 2020-05-19 17:50
Glad you got it working.  I'll add a message displaying the current Ignite JHipster version at the top of the generation process (https://github.com/ruddell/ignite-jhipster/commit/aac871036d5364f83e08bbab9caa0809ffbad0fe)

When generating an `ignite-jhipster` app, it doesn't use a global installation (installing it globally does not matter). `ignite-cli` by default fetches the latest version on npm by default.

This will use the latest version available on `npm`:

    ignite new HelloSchool --boilerplate ignite-jhipster


This will use a specific version available on `npm` instead of the latest:

    ignite new HelloSchool --boilerplate ignite-jhipster@3.5.4
