### ISSUE TITLE
Picker cannot fetch names from jhipster backend

### ISSUE THREAD

**Issue by breechiteri** [ruddell/ignite-jhipster#34] opened 2018-02-26 08:06 UTC
Hi i want the picker to pull enumerator names from the jhipster backend but it return a null value, kindly assist. this is part of my code 

```javascript
 class AssessmentsScreen extends Component {
  constructor(props) {
    super(props);
    this.state = {
      isLoading: false,
      enumerator: '',
      dataSource:[]
    };
  } 
  
  fetchEnumerators = () => {
  this.setState({isLoading: !this.state.isLoading});
  } 
  
  handleLoadMore = () => {
    if (this.state.done || this.props.fetching) {
      return
    }
  this.setState({
    page: this.state.enumerator.name,
    isLoading: true
  })
  this.fetchAssessments()
}
 
  render () {
   
      if (this.state.isLoading) {
        return (
          <View style={{flex: 1, paddingTop: 20}}>
            <ActivityIndicator />
          </View>
        );
      }
     return (
 
 <Picker style={styles.picker}
        itemStyle={styles.items}
        selectedValue={this.state.enumerator.name}
        onValueChange={(itemValue,itemIndex) => this.setState({enumerator: itemValue})}>
            {this.state.dataSource.map((item, key) => {return <Picker.Item value={item.name} label={"Name " + i} key={item.name}  /> })}
            
    </Picker>
	
	)

**Comment by ruddell** [comment] 2018-02-26 16:51
Could you please attach the entity config so I can attempt to reproduce?  Is this a JHipster entity you generated?  In the Angular client, entity enums are hardcoded into a dropdown, so that's what I would advise doing in React Native.

**Comment by breechiteri** [comment] 2018-02-26 17:52
Yes this is a jHipster entity. I did a few things and am now able to fetch
the names (enumerator names ) from the backend. This is what i did.
although it gives a warning (warning :Each child in an array or iterator
should have  a unique key prop )

import React, { Component } from 'react'
import PropTypes from 'prop-types'
import { ScrollView, Text,View,CheckBox,Picker,TouchableOpacity,
ActivityIndicator, Button, Alert} from 'react-native'
import { Table, TableWrapper, Row, Rows, Col, Cols, Cell } from
'react-native-table-component'
import { connect } from 'react-redux'
// Add Actions - replace 'Your' with whatever your reducer is called :)
//import EnumeratorActions from '../Redux/YourRedux'
// Styles
import EnumeratorActions from '../Redux/EnumeratorRedux'
import styles from './Styles/AssessmentsScreenStyle'
import RoundedButton from '../Components/RoundedButton' //
eslint-disable-line
import { Actions as NavigationActions } from 'react-native-router-flux' //
eslint-disable-line



class AssessmentsScreen extends Component {
state = {
page: 0,
sort: 'name,asc',
size: 20,
loading: true,
done: false,
dataObjects: []
}
constructor(props) {
super(props);
this.state = {
isLoading: false,
enumerator: '',
dataObjects:[]
};
}
renderEmpty = () =>
<AlertMessage title='No Enumerators Found' show={!this.props.fetching} />
keyExtractor = (item, index) => index

oneScreensWorth = 20

fetchEnumerators = () => {
this.props.getAllEnumerators({ page: this.state.page, sort: this.state.sort,
size: this.state.size })
}

handleLoadMore = () => {
if (this.state.done || this.props.fetching) {
return
}
this.setState({
page: this.state.page + 1,
loading: true
})
this.fetchEnumerators()
}
componentWillReceiveProps (newProps) {
if (newProps.enumerators) {
this.setState({
done: newProps.enumerators.length < this.state.size,
dataObjects: this.state.loading ? [...this.state.dataObjects, ...newProps.
enumerators] : newProps.enumerators,
loading: false
})
}
}

componentWillMount () {
this.fetchEnumerators()
}
render () {
const tableHead = ['Diet Assessment ID', 'Date', 'State', 'Participant ID',
'Enumerator','Sync'];
const tableData = [
['42', '2.18.2018', 'Open', 'DA001','Brenda'],
['43', '2.19.2018', 'Closed','DA002', 'Mary'],
['44', '2.20.2018', 'Open','DA003', 'Mary'],
];

{
if (this.state.isLoading) {
return (
<View style={{flex: 1, paddingTop: 20}}>
<ActivityIndicator />
</View>
);
}
const values = ['1', '2','3','4'];
return (
<ScrollView >
<View style={styles.Container}>
<View style={{flexDirection: 'row', alignItems: 'center'}}>
<View style={{flex:.5}}>
<Text>Name of Enumerator:</Text>
</View>
<View style={{flex:.5}}>
<Picker>
<Picker.Item label="Brenda" value="brenda"/>
<Picker.Item label="Mary" value="mary"/>
</Picker>
</View>
</View>
</View>


<Picker style={styles.picker}
itemStyle={styles.items}
selectedValue={this.state.enumerator.name}
onValueChange={(value) => this.setState({enumerator: value})}>
{this.state.dataObjects.map((enumerator, name) => {return <Picker.Item value
={enumerator.name} label={"Name of Enumerator:" + enumerator.name} name={
enumerator.name} /> })}
</Picker>
<Table>
<Row data={tableHead} style={styles.head} textStyle={styles.text}/>
<Rows data={tableData} style={styles.row} textStyle={styles.text}/>
</Table>
<RoundedButton text='New Assessment' onPress={NavigationActions.
newAssessment} />
</ScrollView>
)
}
}
}

const mapStateToProps = (state) => {
return {
// ...redux state to props here
enumerators: state.enumerators.enumerators,
fetching: state.enumerators.fetchingAll,
error: state.enumerators.errorAll
}
}

const mapDispatchToProps = (dispatch) => {
return {
getAllEnumerators: (options) => dispatch(EnumeratorActions.
enumeratorAllRequest(options))
}
}

export default connect(mapStateToProps, mapDispatchToProps)(
AssessmentsScreen)

**Comment by ruddell** [comment] 2018-03-01 19:09
That warning is a standard React Native warning, [see this StackOverflow question](https://stackoverflow.com/questions/28329382/understanding-unique-keys-for-array-children-in-react-js).  Since it looks like you resolved the problem, I'm closing this.

**Closed by ruddell** 2018-03-01 19:09 UTC
